## Pacotes

In [1]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.ensemble import RandomForestClassifier

## Leitura de dados

In [2]:
costumers = pd.read_csv('https://raw.githubusercontent.com/edunb01/dotfiles/master/olist_customers_dataset.csv')
itens = pd.read_csv('https://raw.githubusercontent.com/edunb01/dotfiles/master/olist_order_items_dataset.csv')
payments = pd.read_csv('https://raw.githubusercontent.com/edunb01/dotfiles/master/olist_order_payments_dataset.csv')
reviews = pd.read_csv('https://raw.githubusercontent.com/edunb01/dotfiles/master/olist_order_reviews_dataset.csv')
orders = pd.read_csv('https://raw.githubusercontent.com/edunb01/dotfiles/master/olist_orders_dataset.csv')
products = pd.read_csv('https://raw.githubusercontent.com/edunb01/dotfiles/master/olist_products_dataset.csv')
sellers = pd.read_csv('https://raw.githubusercontent.com/edunb01/dotfiles/master/olist_sellers_dataset.csv')

## Consolidando df

In [3]:
df = itens.merge(payments)
df = df.merge(sellers)
df = df.merge(products)
df = df.merge(reviews)
df = df.merge(orders)
df = df.merge(costumers)
df

order_id  order_item_id  \
0       00010242fe8c5a6d1ba2dd792cb16214              1   
1       130898c0987d1801452a8ed92a670612              1   
2       532ed5e14e24ae1f0d735b91524b98b9              1   
3       6f8c31653edb8c83e1a739408b5ff750              1   
4       7d19f4ef4d04461989632411b7e588b9              1   
...                                  ...            ...   
117324  fd607d0a02cb276bc764a15f80f0423f              2   
117325  fdaf98feac227eb978d8f33f36e0231d              1   
117326  fe68b52db13993f58175fa589125d345              1   
117327  ff701a7c869ad21de22a6994237c8a00              1   
117328  ff701a7c869ad21de22a6994237c8a00              2   

                              product_id                         seller_id  \
0       4244733e06e7ecb4970a6e2683c13e61  48436dade18ac8b2bce089ec2a041202   
1       4244733e06e7ecb4970a6e2683c13e61  48436dade18ac8b2bce089ec2a041202   
2       4244733e06e7ecb4970a6e2683c13e61  48436dade18ac8b2bce089ec2a041202   
3       4244733e06e7ecb4970a6e2683c13e61  48436dade18ac8b2bce089ec2a041202   
4       4244733e06e7ecb4970a6e2683c13e61  48436dade18ac8b2bce089ec2a041202   
...                                  ...                               ...   
117324  02ad78835ec3f72e750d1dfa6a7e11b3  2a73cba571d90c694b7caca072ccf6ce   
117325  f739e9151702508b18f796c53005e5e9  d1aa1ec0839dcab73a6161130eb1f94a   
117326  f4135cbdece8245560f7be179533797a  3fefda3299e6dfaea3466ef346a3571a   
117327  5ff4076c0f01eeba4f728c9e3fa2653c  3e35a8bb43569389d3cebef0ce820f69   
117328  5ff4076c0f01eeba4f728c9e3fa2653c  3e35a8bb43569389d3cebef0ce820f69   

        shipping_limit_date   price  freight_value  payment_sequential  \
0       2017-09-19 09:45:35   58.90          13.29                   1   
1       2017-07-05 02:44:11   55.90          17.96                   1   
2       2018-05-23 10:56:25   64.90          18.33                   1   
3       2017-08-07 18:55:08   58.90          16.17                   1   
4       2017-08-16 22:05:11   58.90          13.29                   1   
...                     ...     ...            ...                 ...   
117324  2018-08-02 02:24:15  171.39          19.35                   1   
117325  2017-04-27 05:10:28  119.90          16.14                   1   
117326  2017-08-17 02:55:27  209.00          16.21                   1   
117327  2018-04-18 20:10:33   27.90          14.44                   1   
117328  2018-04-18 20:10:33   27.90          14.44                   1   

       payment_type  payment_installments  ...  order_status  \
0       credit_card                     2  ...     delivered   
1            boleto                     1  ...     delivered   
2       credit_card                     2  ...     delivered   
3       credit_card                     3  ...     delivered   
4       credit_card                     4  ...     delivered   
...             ...                   ...  ...           ...   
117324       boleto                     1  ...     delivered   
117325       boleto                     1  ...     delivered   
117326       boleto                     1  ...     delivered   
117327  credit_card                     1  ...     delivered   
117328  credit_card                     1  ...     delivered   

        order_purchase_timestamp    order_approved_at  \
0            2017-09-13 08:59:02  2017-09-13 09:45:35   
1            2017-06-28 11:52:20  2017-06-29 02:44:11   
2            2018-05-18 10:25:53  2018-05-18 12:31:43   
3            2017-08-01 18:38:42  2017-08-01 18:55:08   
4            2017-08-10 21:48:40  2017-08-10 22:05:11   
...                          ...                  ...   
117324       2018-07-26 09:13:04  2018-07-27 02:24:15   
117325       2017-04-19 10:20:51  2017-04-21 05:10:28   
117326       2017-08-11 10:15:22  2017-08-12 02:55:27   
117327       2018-04-12 19:47:40  2018-04-12 20:10:33   
117328       2018-04-12 19:47:40  2018-04-12 20:10:33   

       order_delivered_carrier_date order_d

## Criando variável que se deseja estudar: Atraso

In [4]:
df['Atraso'] = np.where(df['order_delivered_customer_date'] > df['order_estimated_delivery_date'], 1, 0)

### Verificando colunas disponíveis

In [5]:
df.columns

Index(['order_id', 'order_item_id', 'product_id', 'seller_id',
       'shipping_limit_date', 'price', 'freight_value', 'payment_sequential',
       'payment_type', 'payment_installments', 'payment_value',
       'seller_zip_code_prefix', 'seller_city', 'seller_state',
       'product_category_name', 'product_name_lenght',
       'product_description_lenght', 'product_photos_qty', 'product_weight_g',
       'product_length_cm', 'product_height_cm', 'product_width_cm',
       'review_id', 'review_score', 'review_comment_title',
       'review_comment_message', 'review_creation_date',
       'review_answer_timestamp', 'customer_id', 'order_status',
       'order_purchase_timestamp', 'order_approved_at',
       'order_delivered_carrier_date', 'order_delivered_customer_date',
       'order_estimated_delivery_date', 'customer_unique_id',
       'customer_zip_code_prefix', 'customer_city', 'customer_state',
       'Atraso'],
      dtype='object')

## Engenharia de feature: Criando variáveis dummy para modelagem

In [6]:
df['mesma_cidade'] = np.where(df['seller_city'] == df['customer_city'], 1, 0)
df['mesmo_estado'] = np.where(df['seller_state'] == df['customer_state'], 1, 0)

## Variáveis selecionadas:
seller_id
shipping_limit_date
freight_value
payment_value
product_weight_g
product_length_cm
product_height_cm
product_width_cm
mesma_cidade
mesmo_estado

Modelo:

Criando matriz com variáveis explicativas e resposta. Removendo NA's. Separando em vetor de resposta e matriz de explicativa após ajustar índice.

In [25]:
X = df[['freight_value', 'payment_value', 'product_weight_g', 'product_length_cm', 'product_height_cm', 'product_width_cm', 'mesma_cidade', 'mesmo_estado', "Atraso"]]
X = X.dropna()
X.index = range(len(X))
y = X['Atraso']
X = X.drop(columns=['Atraso'])

freight_value  payment_value  product_weight_g  product_length_cm  \
0               13.29          72.19             650.0               28.0   
1               17.96          73.86             650.0               28.0   
2               18.33          83.23             650.0               28.0   
3               16.17          75.07             650.0               28.0   
4               13.29          72.19             650.0               28.0   
...               ...            ...               ...                ...   
117304          19.35         381.48            1250.0               52.0   
117305          16.14         136.04            1000.0               69.0   
117306          16.21         225.21             500.0               17.0   
117307          14.44          84.68            2000.0               19.0   
117308          14.44          84.68            2000.0               19.0   

        product_height_cm  product_width_cm  mesma_cidade  mesmo_estado  \
0                     9.0              14.0             0             0   
1                     9.0              14.0             0             0   
2                     9.0              14.0             0             0   
3                     9.0              14.0             0             0   
4                     9.0              14.0             0             0   
...                   ...               ...           ...           ...   
117304                7.0              11.0             0             0   
117305               11.0              11.0             0             0   
117306                9.0              25.0             0             0   
117307               38.0              19.0             0             1   
117308               38.0              19.0             0             1   

        Atraso  
0            0  
1            0  
2            0  
3            0  
4            0  
...        ...  
117304       1  
117305       1  
117306       0  
117307       0  
117308       0  

[117309 rows x 9 columns]

Separando em treino/teste (Pode ser removido.)
Modelando, ajustando e predizendo sobre os dados de treino. Mostrando a matriz de confusão

In [27]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3)

model = LogisticRegression()
model.fit(X_train, y_train)
y_pred = model.predict(X_test)
confusion_matrix(y_test, y_pred)


c:\Users\toled\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\linear_model\_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


array([[32489,     0],
       [ 2703,     1]], dtype=int64)

Vemos muitos verdadeiros positivos, poucos verdadeiros negativos, nenhum falso negativo e uma boa quantidade de falsos positivos.

Mesmo procedimento de modelagem, porém com random tree:

In [29]:
model = RandomForestClassifier(n_estimators=1)
model.fit(X_train, y_train)
y_pred = model.predict(X_test)
confusion_matrix(y_test, y_pred)


array([[30532,  1957],
       [ 2169,   535]], dtype=int64)

Mesmo procedimento, porém com random forest

In [30]:
model = RandomForestClassifier()
model.fit(X_train, y_train)
y_pred = model.predict(X_test)
confusion_matrix(y_test, y_pred)

array([[32054,   435],
       [ 2234,   470]], dtype=int64)

Vemos daqui que regressão logistica binária e florestas aleatórias tiveram desempenho parecido para estes dados.